namespace FarmManagement.API.DTOs;
public record CropVarietyDto(string Crop,string Variety,string? Notes);
public record CropPlantingDto(string Crop,string Field,DateTime Planted,DateTime ExpectedHarvest,string? Stage);
public record CropActivityDto(string Type,string Text,string Who);
public record CropObservationDto(string Field,string Text,string Severity,string Who);
public record HarvestDto(string Crop,string Field,DateTime Date,decimal Quantity,string Unit);
public record LivestockBatchDto(string Name,string Size,string Purpose,string Stage);
public record LivestockHealthDto(string Batch,string Text,string Who);
public record VaccinationDto(string Batch,string Vaccine,DateTime Due);
public record LivestockLogDto(string Type,string Text,string Who);
public record LivestockProductionDto(string Batch,string Metric,string Value,DateTime Date);
public record LivestockBreedingDto(string Batch,string Event,DateTime Date,string? Notes);
public record InventoryItemDto(string Item,string Category,decimal Quantity,string Unit,decimal Reorder);
public record InventoryUsageDto(string Item,decimal Quantity,string Unit,string UsedFor,string Who);
public record SupplierDto(string Name,string Contact,string Category);
public record PurchaseLogDto(string Type,string Text,string Who);
public record OperatingCostDto(DateTime Date,string Category,string Description,decimal Amount);
public record FarmTaskDto(string Title,string? Link,string Assignee,string Priority,DateTime Deadline);
public record TaskStatusDto(string Status);
